# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: bot1

on:
  schedule: # AM 11:50 / PM 2:50 / PM 5:50 / PM 8:50 / PM 11:50
    - cron:  "50 02 * * *"
    - cron:  "50 05 * * *"
    - cron:  "50 08 * * *"
    - cron:  "50 11 * * *"
    - cron:  "50 14 * * *"
    - cron:  "27 07 * * *"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK1 }}
        content: "결계탐"
