# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: bot1

on:
  schedule: # AM 11:45 / PM 2:45 / PM 5:45 / PM 8:45 / PM 11:45
    - cron:  "45 02 * * *"
    - cron:  "45 05 * * *"
    - cron:  "45 08 * * *"
    - cron:  "45 11 * * *"
    - cron:  "45 14 * * *"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK1 }}
        content: "결계ㄱㄱ"
